/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "mount.h"
#include <stdio.h>
#include <stdlib.h> /* getenv, exit */
#include <signal.h>
#include <sys/types.h>
#include <memory.h>
#include <stropts.h>
#include <netconfig.h>
#include <sys/resource.h> /* rlimit */
#include <syslog.h>

#ifdef DEBUG
#define	RPC_SVC_FG
#endif

#define	_RPCSVC_CLOSEDOWN 120

#define	fhs_fh	fhstatus_u.fhs_fhandle
static int _rpcpmstart;		/* Started by a port monitor ? */

/* States a server can be in wrt request */

#define	_IDLE 0
#define	_SERVED 1

static int _rpcsvcstate = _IDLE;	/* Set when a request is serviced */
static int _rpcsvccount = 0;		/* Number of requests being serviced */

static
void _msgout(msg)
	char *msg;
{
#ifdef RPC_SVC_FG
	if (_rpcpmstart)
		syslog(LOG_ERR, msg);
	else
		(void) fprintf(stderr, "%s\n", msg);
#else
	syslog(LOG_ERR, msg);
#endif
}

static void
closedown(sig)
	int sig;
{
	if (_rpcsvcstate == _IDLE && _rpcsvccount == 0) {
		extern fd_set svc_fdset;
		static int size;
		int i, openfd;
		struct t_info tinfo;

		if (!t_getinfo(0, &tinfo) && (tinfo.servtype == T_CLTS))
			exit(0);
		if (size == 0) {
			struct rlimit rl;

			rl.rlim_max = 0;
			getrlimit(RLIMIT_NOFILE, &rl);
			if ((size = rl.rlim_max) == 0) {
				return;
			}
		}
		for (i = 0, openfd = 0; i < size && openfd < 2; i++)
			if (FD_ISSET(i, &svc_fdset))
				openfd++;
		if (openfd <= 1)
			exit(0);
	} else
		_rpcsvcstate = _IDLE;

	(void) signal(SIGALRM, (void(*)()) closedown);
	(void) alarm(_RPCSVC_CLOSEDOWN/2);
}

static void
mountprog_1(rqstp, transp)
	struct svc_req *rqstp;
	register SVCXPRT *transp;
{
	union {
		dirpath mountproc_mnt_1_arg;
		dirpath mountproc_umnt_1_arg;
	} argument;
	char *result;
	bool_t (*_xdr_argument)(), (*_xdr_result)();
	char *(*local)();

	_rpcsvccount++;
	switch (rqstp->rq_proc) {
	case MOUNTPROC_NULL:
		_xdr_argument = xdr_void;
		_xdr_result = xdr_void;
		local = (char *(*)()) mountproc_null_1;
		break;

	case MOUNTPROC_MNT:
		_xdr_argument = xdr_dirpath;
		_xdr_result = xdr_fhstatus;
		local = (char *(*)()) mountproc_mnt_1;
		break;

	case MOUNTPROC_DUMP:
		_xdr_argument = xdr_void;
		_xdr_result = xdr_mountlist;
		local = (char *(*)()) mountproc_dump_1;
		break;

	case MOUNTPROC_UMNT:
		_xdr_argument = xdr_dirpath;
		_xdr_result = xdr_void;
		local = (char *(*)()) mountproc_umnt_1;
		break;

	case MOUNTPROC_UMNTALL:
		_xdr_argument = xdr_void;
		_xdr_result = xdr_void;
		local = (char *(*)()) mountproc_umntall_1;
		break;

	case MOUNTPROC_EXPORT:
		_xdr_argument = xdr_void;
		_xdr_result = xdr_exports;
		local = (char *(*)()) mountproc_export_1;
		break;

	case MOUNTPROC_EXPORTALL:
		_xdr_argument = xdr_void;
		_xdr_result = xdr_exports;
		local = (char *(*)()) mountproc_exportall_1;
		break;

	default:
		svcerr_noproc(transp);
		_rpcsvccount--;
		_rpcsvcstate = _SERVED;
		return;
	}
	(void) memset((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs(transp, _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode(transp);
		_rpcsvccount--;
		_rpcsvcstate = _SERVED;
		return;
	}
	result = (*local)(&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, _xdr_result, result)) {
		svcerr_systemerr(transp);
	}
	if (!svc_freeargs(transp, _xdr_argument, (caddr_t) &argument)) {
		_msgout("unable to free arguments");
		exit(1);
	}
	_rpcsvccount--;
	_rpcsvcstate = _SERVED;
	return;
}

static void
mountprog_2(rqstp, transp)
	struct svc_req *rqstp;
	register SVCXPRT *transp;
{
	union {
		dirpath mountproc_mnt_2_arg;
		dirpath mountproc_umnt_2_arg;
		dirpath mountproc_pathconf_2_arg;
	} argument;
	char *result;
	bool_t (*_xdr_argument)(), (*_xdr_result)();
	char *(*local)();

	_rpcsvccount++;
	switch (rqstp->rq_proc) {
	case MOUNTPROC_NULL:
		_xdr_argument = xdr_void;
		_xdr_result = xdr_void;
		local = (char *(*)()) mountproc_null_2;
		break;

	case MOUNTPROC_MNT:
		_xdr_argument = xdr_dirpath;
		_xdr_result = xdr_fhstatus;
		local = (char *(*)()) mountproc_mnt_2;
		break;

	case MOUNTPROC_DUMP:
		_xdr_argument = xdr_void;
		_xdr_result = xdr_mountlist;
		local = (char *(*)()) mountproc_dump_2;
		break;

	case MOUNTPROC_UMNT:
		_xdr_argument = xdr_dirpath;
		_xdr_result = xdr_void;
		local = (char *(*)()) mountproc_umnt_2;
		break;

	case MOUNTPROC_UMNTALL:
		_xdr_argument = xdr_void;
		_xdr_result = xdr_void;
		local = (char *(*)()) mountproc_umntall_2;
		break;

	case MOUNTPROC_EXPORT:
		_xdr_argument = xdr_void;
		_xdr_result = xdr_exports;
		local = (char *(*)()) mountproc_export_2;
		break;

	case MOUNTPROC_EXPORTALL:
		_xdr_argument = xdr_void;
		_xdr_result = xdr_exports;
		local = (char *(*)()) mountproc_exportall_2;
		break;

	case MOUNTPROC_PATHCONF:
		_xdr_argument = xdr_dirpath;
		_xdr_result = xdr_ppathcnf;
		local = (char *(*)()) mountproc_pathconf_2;
		break;

	default:
		svcerr_noproc(transp);
		_rpcsvccount--;
		_rpcsvcstate = _SERVED;
		return;
	}
	(void) memset((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs(transp, _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode(transp);
		_rpcsvccount--;
		_rpcsvcstate = _SERVED;
		return;
	}
	result = (*local)(&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, _xdr_result, result)) {
		svcerr_systemerr(transp);
	}
	if (!svc_freeargs(transp, _xdr_argument, (caddr_t) &argument)) {
		_msgout("unable to free arguments");
		exit(1);
	}
	_rpcsvccount--;
	_rpcsvcstate = _SERVED;
	return;
}

static void
mountprog_3(rqstp, transp)
	struct svc_req *rqstp;
	register SVCXPRT *transp;
{
	union {
		dirpath mountproc_mnt_3_arg;
		dirpath mountproc_umnt_3_arg;
	} argument;
	char *result;
	bool_t (*_xdr_argument)(), (*_xdr_result)();
	char *(*local)();

	_rpcsvccount++;
	switch (rqstp->rq_proc) {
	case MOUNTPROC_NULL:
		_xdr_argument = xdr_void;
		_xdr_result = xdr_void;
		local = (char *(*)()) mountproc_null_3;
		break;

	case MOUNTPROC_MNT:
		_xdr_argument = xdr_dirpath;
		_xdr_result = xdr_mountres3;
		local = (char *(*)()) mountproc_mnt_3;
		break;

	case MOUNTPROC_DUMP:
		_xdr_argument = xdr_void;
		_xdr_result = xdr_mountlist;
		local = (char *(*)()) mountproc_dump_3;
		break;

	case MOUNTPROC_UMNT:
		_xdr_argument = xdr_dirpath;
		_xdr_result = xdr_void;
		local = (char *(*)()) mountproc_umnt_3;
		break;

	case MOUNTPROC_UMNTALL:
		_xdr_argument = xdr_void;
		_xdr_result = xdr_void;
		local = (char *(*)()) mountproc_umntall_3;
		break;

	case MOUNTPROC_EXPORT:
		_xdr_argument = xdr_void;
		_xdr_result = xdr_exports;
		local = (char *(*)()) mountproc_export_3;
		break;

	default:
		svcerr_noproc(transp);
		_rpcsvccount--;
		_rpcsvcstate = _SERVED;
		return;
	}
	(void) memset((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs(transp, _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode(transp);
		_rpcsvccount--;
		_rpcsvcstate = _SERVED;
		return;
	}
	result = (*local)(&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, _xdr_result, result)) {
		svcerr_systemerr(transp);
	}
	if (!svc_freeargs(transp, _xdr_argument, (caddr_t) &argument)) {
		_msgout("unable to free arguments");
		exit(1);
	}
	_rpcsvccount--;
	_rpcsvcstate = _SERVED;
	return;
}

main()
{
	pid_t pid;
	int i;

	(void) sigset(SIGPIPE, SIG_IGN);

	/*
	 * If stdin looks like a TLI endpoint, we assume
	 * that we were started by a port monitor. If
	 * t_getstate fails with TBADF, this is not a
	 * TLI endpoint.
	 */
	if (t_getstate(0) != -1 || t_errno != TBADF) {
		char *netid;
		struct netconfig *nconf = NULL;
		SVCXPRT *transp;
		int pmclose;

		_rpcpmstart = 1;
		openlog("mount", LOG_PID, LOG_DAEMON);

		if ((netid = getenv("NLSPROVIDER")) == NULL) {
		/* started from inetd */
			pmclose = 1;
		} else {
			if ((nconf = getnetconfigent(netid)) == NULL)
				_msgout("cannot get transport info");

			pmclose = (t_getstate(0) != T_DATAXFER);
		}
		if ((transp = svc_tli_create(0, nconf, NULL, 0, 0)) == NULL) {
			_msgout("cannot create server handle");
			exit(1);
		}
		if (nconf)
			freenetconfigent(nconf);
		if (!svc_reg(transp, MOUNTPROG, MOUNTVERS, mountprog_1, 0)) {
			_msgout("unable to register (MOUNTPROG, MOUNTVERS).");
			exit(1);
		}
		if (!svc_reg(transp, MOUNTPROG, MOUNTVERS_POSIX, mountprog_2, 0)) {
			_msgout("unable to register (MOUNTPROG, MOUNTVERS_POSIX).");
			exit(1);
		}
		if (!svc_reg(transp, MOUNTPROG, MOUNTVERS3, mountprog_3, 0)) {
			_msgout("unable to register (MOUNTPROG, MOUNTVERS3).");
			exit(1);
		}
		if (pmclose) {
			(void) signal(SIGALRM, (void(*)()) closedown);
			(void) alarm(_RPCSVC_CLOSEDOWN/2);
		}
		svc_run();
		exit(1);
		/* NOTREACHED */
	}	else {
#ifndef RPC_SVC_FG
		int size;
		struct rlimit rl;
		pid = fork();
		if (pid < 0) {
			perror("cannot fork");
			exit(1);
		}
		if (pid)
			exit(0);
		rl.rlim_max = 0;
		getrlimit(RLIMIT_NOFILE, &rl);
		if ((size = rl.rlim_max) == 0)
			exit(1);
		for (i = 0; i < size; i++)
			(void) close(i);
		i = open("/dev/null", 2);
		(void) dup2(i, 1);
		(void) dup2(i, 2);
		setsid();
		openlog("mount", LOG_PID, LOG_DAEMON);
#endif
	}
	if (!svc_create(mountprog_1, MOUNTPROG, MOUNTVERS, "netpath")) {
		_msgout("unable to create (MOUNTPROG, MOUNTVERS) for netpath.");
		exit(1);
	}
	if (!svc_create(mountprog_2, MOUNTPROG, MOUNTVERS_POSIX, "netpath")) {
		_msgout("unable to create (MOUNTPROG, MOUNTVERS_POSIX) for netpath.");
		exit(1);
	}
	if (!svc_create(mountprog_3, MOUNTPROG, MOUNTVERS3, "netpath")) {
		_msgout("unable to create (MOUNTPROG, MOUNTVERS3) for netpath.");
		exit(1);
	}

	svc_run();
	_msgout("svc_run returned");
	exit(1);
	/* NOTREACHED */
}
